language: node_js

node_js:
  - "8"
  - "10"

install:
  - yarn global add codecov
  - yarn
  - yarn add --peer web3@1.0.0-beta.37 @nomiclabs/buidler@^1.0.0-alpha.5

script:
  - yarn test
  - codecov
  - yarn lint

cache: yarn

branches:
  only:
    - master
